name: carma
description: "Track vehicle expenses and odometer with AI"
publish_to: 'none'

version: 1.0.5+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it:
  intl: ^0.18.0
  fl_chart: ^0.69.0
  flutter_lints: ^3.0.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc:
  rxdart:
#  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
#  flutter_background_service: ^5.0.10
#  workmanager: ^0.5.0
  audioplayers: ^6.1.0
  haptic_feedback: 0.5.1
  dartz: ^0.10.1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.3
  share_plus: ^10.1.3
  http: ^1.2.2
  http_parser: ^4.0.2
  mime: ^2.0.0
  image_picker:
  flutter_animate: ^4.5.2
  mixpanel_flutter: ^2.3.3
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  package_info_plus: ^8.1.2
  webview_flutter: ^4.8.0
  path_provider: ^2.1.5
  flutter_picker: ^2.1.0
  flutter_launcher_icons: ^0.14.2
  superwallkit_flutter: ^1.3.9
  purchases_flutter: ^8.4.4
  in_app_review: ^2.0.10
  onboarding: ^4.0.2
  app_tracking_transparency: ^2.0.6+1
  icloud_storage: ^2.2.0
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/digital-7.ttf
  assets:
    - assets/images/
    - assets/sounds/